#!/bin/bash
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
fi

# if [ -z "$1" ]; then
#   echo "Pass the number of the namespace to connect from"
#   return 1
# fi

echo "Starting client in namespace \"space3\""
echo "Connecting to ip: 192.168.0.30:4444"
echo ""
echo "# ip netns exec space3 python3 client.py 192.168.0.30 4444"
ip netns exec space3 python3 client.py 192.168.0.30 4444
