#!/bin/bash
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
fi

echo "Starting server in namespace \"space2\""
echo "Running server on 192.168.0.30:4444"

ip netns exec space2 python3 server.py 192.168.0.30 4444
